// Generated by CoffeeScript 1.12.4
(function() {
  exports.EXTENSIONS = {
    ".coffee": {
      js_extension: ".js"
    },
    ".cjsx": {
      js_extension: ".js"
    },
    ".litcoffee": {
      js_extension: ".js"
    },
    ".coffee.md": {
      js_extension: ".js"
    },
    "._coffee": {
      js_extension: "._js"
    }
  };

}).call(this);
